-- 清理存量 STORAGE_QUOTA 关联（PG 不允许删除正在使用的枚举值，必须先清数据）
DELETE FROM "role_permissions" WHERE "permission" = 'STORAGE_QUOTA';

BEGIN;
CREATE TYPE "Permission_new" AS ENUM ('SYSTEM_USER_READ', 'SYSTEM_USER_CREATE', 'SYSTEM_USER_UPDATE', 'SYSTEM_USER_DELETE', 'SYSTEM_USER_MEMBERSHIP_MANAGE', 'SYSTEM_ROLE_READ', 'SYSTEM_ROLE_CREATE', 'SYSTEM_ROLE_UPDATE', 'SYSTEM_ROLE_DELETE', 'SYSTEM_ROLE_PERMISSION_MANAGE', 'SYSTEM_FONT_READ', 'SYSTEM_FONT_UPLOAD', 'SYSTEM_FONT_DELETE', 'SYSTEM_FONT_DOWNLOAD', 'SYSTEM_ADMIN', 'SYSTEM_BILLING_READ', 'SYSTEM_BILLING_WRITE', 'SYSTEM_MONITOR', 'SYSTEM_CONFIG_READ', 'SYSTEM_CONFIG_WRITE', 'SYSTEM_IP_BLACKLIST_MANAGE', 'LIBRARY_DRAWING_MANAGE', 'LIBRARY_BLOCK_MANAGE', 'PROJECT_CREATE');
ALTER TABLE "role_permissions" ALTER COLUMN "permission" TYPE "Permission_new" USING ("permission"::text::"Permission_new");
ALTER TABLE "policy_permissions" ALTER COLUMN "permission" TYPE "Permission_new" USING ("permission"::text::"Permission_new");
ALTER TYPE "Permission" RENAME TO "Permission_old";
ALTER TYPE "Permission_new" RENAME TO "Permission";
DROP TYPE "public"."Permission_old";
COMMIT;
