-- Baseline migration to fix drift between migration history and current schema
-- Generated by prisma migrate diff --from-migrations --to-schema

-- AlterEnum: Add new values to AuditAction
ALTER TYPE "AuditAction" ADD VALUE 'USER_REGISTER';
ALTER TYPE "AuditAction" ADD VALUE 'USER_VERIFY_EMAIL';
ALTER TYPE "AuditAction" ADD VALUE 'USER_BIND_EMAIL';
ALTER TYPE "AuditAction" ADD VALUE 'USER_UNBIND_EMAIL';
ALTER TYPE "AuditAction" ADD VALUE 'USER_BIND_PHONE';
ALTER TYPE "AuditAction" ADD VALUE 'USER_UNBIND_PHONE';
ALTER TYPE "AuditAction" ADD VALUE 'USER_REBIND_EMAIL';
ALTER TYPE "AuditAction" ADD VALUE 'USER_REBIND_PHONE';
ALTER TYPE "AuditAction" ADD VALUE 'USER_BIND_WECHAT';
ALTER TYPE "AuditAction" ADD VALUE 'USER_UNBIND_WECHAT';
ALTER TYPE "AuditAction" ADD VALUE 'USER_CHANGE_PASSWORD';
ALTER TYPE "AuditAction" ADD VALUE 'USER_DEACTIVATE';
ALTER TYPE "AuditAction" ADD VALUE 'PROJECT_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE 'PROJECT_TRANSFER';

-- AlterEnum: Remove SYSTEM_TEMPLATE_READ from Permission
BEGIN;
CREATE TYPE "Permission_new" AS ENUM ('SYSTEM_USER_READ', 'SYSTEM_USER_CREATE', 'SYSTEM_USER_UPDATE', 'SYSTEM_USER_DELETE', 'SYSTEM_ROLE_READ', 'SYSTEM_ROLE_CREATE', 'SYSTEM_ROLE_UPDATE', 'SYSTEM_ROLE_DELETE', 'SYSTEM_ROLE_PERMISSION_MANAGE', 'SYSTEM_FONT_READ', 'SYSTEM_FONT_UPLOAD', 'SYSTEM_FONT_DELETE', 'SYSTEM_FONT_DOWNLOAD', 'SYSTEM_ADMIN', 'SYSTEM_BILLING_READ', 'SYSTEM_BILLING_WRITE', 'SYSTEM_MONITOR', 'SYSTEM_CONFIG_READ', 'SYSTEM_CONFIG_WRITE', 'LIBRARY_DRAWING_MANAGE', 'LIBRARY_BLOCK_MANAGE', 'STORAGE_QUOTA', 'PROJECT_CREATE');
ALTER TABLE "role_permissions" ALTER COLUMN "permission" TYPE "Permission_new" USING ("permission"::text::"Permission_new");
ALTER TABLE "policy_permissions" ALTER COLUMN "permission" TYPE "Permission_new" USING ("permission"::text::"Permission_new");
ALTER TYPE "Permission" RENAME TO "Permission_old";
ALTER TYPE "Permission_new" RENAME TO "Permission";
DROP TYPE "public"."Permission_old";
COMMIT;

-- AlterEnum: Remove GALLERY_ADD from ProjectPermission
BEGIN;
CREATE TYPE "ProjectPermission_new" AS ENUM ('PROJECT_UPDATE', 'PROJECT_DELETE', 'PROJECT_MEMBER_MANAGE', 'PROJECT_MEMBER_ASSIGN', 'PROJECT_TRANSFER', 'PROJECT_ROLE_MANAGE', 'PROJECT_ROLE_PERMISSION_MANAGE', 'FILE_CREATE', 'FILE_UPLOAD', 'FILE_OPEN', 'FILE_EDIT', 'FILE_DELETE', 'FILE_TRASH_MANAGE', 'FILE_DOWNLOAD', 'FILE_SHARE', 'FILE_MOVE', 'FILE_COPY', 'CAD_SAVE', 'CAD_EXTERNAL_REFERENCE', 'VERSION_READ');
ALTER TABLE "project_role_permissions" ALTER COLUMN "permission" TYPE "ProjectPermission_new" USING ("permission"::text::"ProjectPermission_new");
ALTER TYPE "ProjectPermission" RENAME TO "ProjectPermission_old";
ALTER TYPE "ProjectPermission_new" RENAME TO "ProjectPermission";
DROP TYPE "public"."ProjectPermission_old";
COMMIT;

-- DropForeignKey
ALTER TABLE "file_shares" DROP CONSTRAINT IF EXISTS "cooperate_shares_createdBy_fkey";

-- DropIndex
DROP INDEX IF EXISTS "idx_file_system_nodes_description_trgm";
DROP INDEX IF EXISTS "idx_file_system_nodes_name_trgm";
DROP INDEX IF EXISTS "idx_file_system_nodes_search_vector";

-- AlterTable: file_shares
ALTER TABLE "file_shares" RENAME CONSTRAINT "cooperate_shares_pkey" TO "file_shares_pkey";

-- AlterTable: membership_plans
ALTER TABLE "membership_plans" ALTER COLUMN "tier" SET DEFAULT 'PRO';

-- AlterTable: payment_orders
ALTER TABLE "payment_orders" DROP COLUMN IF EXISTS "refund_reason",
ADD COLUMN IF NOT EXISTS "refundReason" TEXT;

-- AlterTable: users
ALTER TABLE "users" ALTER COLUMN "usernameChangeCount" SET NOT NULL;

-- CreateTable: vip_tiers
CREATE TABLE IF NOT EXISTS "vip_tiers" (
    "id" TEXT NOT NULL,
    "level" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "baseMonthlyPrice" INTEGER NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "configs" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "vip_tiers_pkey" PRIMARY KEY ("id")
);

-- CreateTable: duration_pricings
CREATE TABLE IF NOT EXISTS "duration_pricings" (
    "id" TEXT NOT NULL,
    "months" INTEGER NOT NULL,
    "multiplierBps" INTEGER NOT NULL,
    "label" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "duration_pricings_pkey" PRIMARY KEY ("id")
);

-- CreateTable: config_key_registry
CREATE TABLE IF NOT EXISTS "config_key_registry" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "defaultValue" JSONB,
    "description" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "config_key_registry_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "vip_tiers_level_key" ON "vip_tiers"("level");
CREATE UNIQUE INDEX IF NOT EXISTS "duration_pricings_months_key" ON "duration_pricings"("months");
CREATE UNIQUE INDEX IF NOT EXISTS "config_key_registry_key_key" ON "config_key_registry"("key");

-- AddForeignKey (only if not already exists - checked via IF NOT EXISTS pattern)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'file_shares_createdBy_fkey'
    ) THEN
        ALTER TABLE "file_shares" ADD CONSTRAINT "file_shares_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
    END IF;
END $$;

-- RenameIndex (only if old name exists)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'cooperate_shares_createdBy_idx') THEN
        ALTER INDEX "cooperate_shares_createdBy_idx" RENAME TO "file_shares_createdBy_idx";
    END IF;
    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'cooperate_shares_fileId_idx') THEN
        ALTER INDEX "cooperate_shares_fileId_idx" RENAME TO "file_shares_fileId_idx";
    END IF;
    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'cooperate_shares_token_idx') THEN
        ALTER INDEX "cooperate_shares_token_idx" RENAME TO "file_shares_token_idx";
    END IF;
    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'cooperate_shares_token_key') THEN
        ALTER INDEX "cooperate_shares_token_key" RENAME TO "file_shares_token_key";
    END IF;
    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'file_system_nodes_node_type_idx') THEN
        ALTER INDEX "file_system_nodes_node_type_idx" RENAME TO "file_system_nodes_nodeType_idx";
    END IF;
    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'roles_name_unique') THEN
        ALTER INDEX "roles_name_unique" RENAME TO "roles_name_key";
    END IF;
END $$;
