///////////////////////////////////////////////////////////////////////////////
// ‍ 版权所有（C）2002-2022，成都梦想凯德科技有限公司。
// ‍ Copyright (C) 2002-2022, Chengdu Dream Kaide Technology Co., Ltd.

// ‍ 本软件代码及其文档和相关资料归成都梦想凯德科技有限公司,应用包含本软件的程序必须包括以下版权声明
// ‍ The code, documentation, and related materials of this software belong to Chengdu Dream Kaide Technology Co., Ltd. Applications that include this software must include the following copyright statement

// ‍ 此应用程序应与成都梦想凯德科技有限公司达成协议，使用本软件、其文档或相关材料
// ‍ This application should reach an agreement with Chengdu Dream Kaide Technology Co., Ltd. to use this software, its documentation, or related materials

//https://www.mxdraw.com/
///////////////////////////////////////////////////////////////////////////////

//@ts-nocheck
import WebUploader from "webuploader";
import $api from "../axios/index";
import { getUploadFileConfig } from "@/config/serverConfig";

export interface UploaderRegisterConfig {
  /**
* css选择器规范 通常采用id 如 #id, 选择文件的按钮。 内部根据当前运行是创建，可能是input元素，也可能是flash
/**CSS selector specifications typically use IDs such as # id and buttons to select files. Internally, based on the current runtime, it may be an input element or a flash

   *
innerHTML {String} 指定按钮文字。不指定时优先从指定的容器中看是否自带文字。
InnerHTML {String} specifies the button text. When not specified, priority should be given to checking whether the specified container has built-in text.

multiple {Boolean} 是否开起同时选择多个文件能力。
Does multiple {Boolean} have the ability to select multiple files simultaneously.

   * . */
  pick?:
  | string
  | {
    /** id {Seletor|dom} 指定选择文件的按钮容器，不指定则不创建按钮。注意 这里虽然写的是 id, 但是不是只支持 id, 还支持 class, 或者 dom 节点。 */
    id?: string;
    /** {String} 请采用 innerHTML 代替 */
    label?: string;
    /** {String} 指定按钮文字。不指定时优先从指定的容器中看是否自带文字。 */
    innerHTML?: string;
    /** 是否开起同时选择多个文件能力。  */
    multiple?: boolean;
  };
  /** 上传失败回调 */
  onError?: () => void;
  /** 文件接收的后台服务器接口 */
  serverURL?: string;
  /** 文件上传排队时触发函数 */
  onFileQueued?: (file: any) => void | boolean | Promise<any>;

  /** 文件上传进度监听进度触发函数
/**File upload progress monitoring progress trigger function

   * @param percentage 百分比进度
*@ param percentage progress

   */
  onProgress?: (percentage: number) => void;
  /** 文件上传前生成hash值的进度触发函数
/**The progress trigger function for generating hash values before file upload

   * @param percentage 百分比进度
   */
  onCreateHashProgress?: (percentage: number) => void;
  /** 文件开始上传触发回调函数
/**Starting file upload triggers callback function

   * @param percentage 百分比进度
   */
  onBeginUpload?: () => void;

  /** 服务器检测到文件hash值已存在，秒传 触发该回调函数
/**The server has detected that the file hash value already exists, triggering the callback function in seconds

   */
  onSecondTransmission?: () => void;

  /** 文件上传成功
/**File uploaded successfully

   * @param file 文件对象
*@ param file object

   * @param hash 该文件生成的hash值
*@ param hash The hash value generated by this file

   *  */
  onUploadSuccess?: (
    file: any,
    hash: string,
    isUseExistingFile: boolean
  ) => void;

  /**所有文件上传成功 */
  onUploadFinished?: () => void;

  /** 上传文件的类型 */
  accept?: {
    extensions: string;
    mimeTypes: string;
  };
}

export function getHostUrl(): string {
  let host = window.location.hostname;
  if (host.substring(0, 4) != "http") {
    host = document.location.protocol + "//" + host;
  }
  return host;
}

let isReloadFile = false;

export function setReloadFile(isReload: boolean) {
  isReloadFile = isReload;
}
let uploader: any;
export const getUploader = () => {
  return uploader;
};
/** 创建文件上传器上传器
/**Create file uploader uploader

 * @parma config 注册上传器需要的配置
*@ parma config registration uploader requires configuration

 *  */
export function createDwgFileUploader(config: UploaderRegisterConfig) {
  let {
    create,
    baseUrl = "",
    fileisExist,
    chunkisExist,
    chunked,
  } = getUploadFileConfig() || {};

  if (baseUrl.substring(0, 16) == "http://localhost") {
    baseUrl = getHostUrl() + baseUrl.substring(16);
  }

  let { swf, server = "", accept } = create || {};
  const {
    pick,
    serverURL,
    onError,
    onFileQueued,
    onCreateHashProgress,
    onProgress,
    onBeginUpload,
    onSecondTransmission,
    onUploadSuccess,
    onUploadFinished,
    accept: _accept,
  } = config;
  accept = _accept || accept;
  let hash = "";
  WebUploader.Uploader.register(
    {
      "before-send": "beforeSend",
    },
    {
      beforeSend: (block: any) => {

        if (isReloadFile) {
          return true;
        }
        else {

          // ‍  分片文件准备上传，判断一下服务是否已经有了，如果有了，就来再上传.
          // ‍ Prepare to upload fragmented files, check if the service is already available, and if so, come and upload again

          const deferred = WebUploader.Deferred();
          $api
            .post(baseUrl + chunkisExist, {
              chunk: block.chunk,
              chunks: block.chunks,
              fileName: block.file.name,
              fileHash: hash,
              size: block.blob.size,
            })
            .then(
              (res: any) => {
                if (res.data.ret == "chunkAlreadyExist") {
                  // ‍  分片存在
                  // ‍ Sharding exists

                  deferred.reject();
                } else {
                  // ‍  分片不存在
                  // ‍ Sharding does not exist

                  deferred.resolve();
                }
              },
              () => {
                console.log("MxTip:post chunk is Exits error");
                onError && onError();
              }
            );
          return deferred.promise();
        }

      },
    }
  );

  uploader = WebUploader.create({
    // ‍ 是否允许重复的图片
    // ‍ Do you allow duplicate images

    //duplicate: true,
    preserveHeaders: true, // ‍  是否保留头部meta信息。
    // ‍ Should the header meta information be retained.

    withCredentials: true, // ‍ 携带Cookie
    // ‍ Carrying cookies

    auto: false, // ‍  选完文件后，是否自动上传
    // ‍ After selecting the file, will it be automatically uploaded

    swf, // ‍  swf文件路径
    // ‍ SWF file path

    server: serverURL || baseUrl + server, // ‍  文件接收服务端  接收接口
    // ‍ File receiving server receiving interface

    pick,
    resize: false, // ‍ 上传前不压缩
    // ‍ Do not compress before uploading

    duplicate: false,
    // ‍ 线程数
    // ‍ Number of threads

    threads: 3,
    chunked: chunked,
    // ‍ chunkSize:checkSize,//每个分片的大小，默认5M
    // ‍ ChunkSize: checkSize,//the size of each shard, default 5M

    // ‍ 单个文件大小限制
    // ‍ Single file size limit

    //fileSingleSizeLimit: 2000,
    // ‍ 上传文件数量限制
    // ‍ Upload file quantity limit

    fileNumLimit: 2,
    timeout: 2601000, // ‍ 超时时间
    // ‍ Timeout period

    // ‍ 文件类型
    // ‍ File type

    accept: accept || {
      extensions: "dwg,DWG,dxf,DXF,mxweb",
      mimeTypes: ".dwg,.DwG,.dxf,.DXF,.mxweb",
    },
  });

  // 解決IOS 打开文件调用摄像问题
  if (pick instanceof HTMLDivElement) {
    setTimeout(() => {
      const input = pick.getElementsByTagName("input")[0];
      input.removeAttribute("capture");
    }, 1000);
  } else {
    let el: HTMLDivElement;
    if (typeof pick === "string") {
      const el = document.querySelector(
        pick.startsWith("#") ? pick : "#" + pick
      );
    } else if (typeof pick === "object") {
      const { id } = pick;
      if (!id) return console.warn(`上传DOM pick参数没有id属性`);
      const el = document.querySelector(pick.startsWith("#") ? id : "#" + pick);
      setTimeout(() => {
        const input = el.getElementsByTagName("input")[0];
        input.removeAttribute("capture");
      }, 1000);
    }
  }
  // ‍  文件排队
  // ‍ File queue

  uploader.on("fileQueued", async (file: any) => {
    console.log("file: ", file)
    if (onFileQueued && await onFileQueued(file)) {
      return;
    }
    // ‍  检查生成hash 上传文件
    // ‍ Check the generated hash upload file

    uploader
      .md5File(file)
      .progress((percentage: any) => {
        onCreateHashProgress && onCreateHashProgress(percentage);
      })
      .then((fileHash: string) => {
        hash = fileHash;
        console.log("fileHash: ", fileHash);
        if (isReloadFile) {
          onBeginUpload && onBeginUpload();
          uploader.upload();
        } else {
          if (file.ext === "mxweb") {
            // ‍  mxweb,就直接打开，这里不需要上传转换。 onFileQueued调用打开.
            // ‍ MXWeb, just open it directly without uploading or converting. Call onFileQueued to open

            uploader.skipFile(file);
            uploader.reset();
          } else {
            // ‍  判断文件在服务上是否已经存在，如果已经存在，就不上传了
            // ‍ Check if the file already exists on the service. If it already exists, do not upload it

            $api
              .post(baseUrl + fileisExist, {
                fileHash,
                filename: file.name,
              })
              .then(
                (res) => {
                  onBeginUpload && onBeginUpload();
                  if (res.data.ret == "fileAlreadyExist") {
                    onSecondTransmission && onSecondTransmission();
                    uploader.skipFile(file);
                    uploader.reset();
                    onUploadSuccess && onUploadSuccess(file, hash, false);
                  } else {
                    uploader.upload();
                  }
                },
                () => {
                  console.log("MxTip:post file is Exits error:1");
                  onError && onError();
                }
              );
          }
        }
      });
  });

  uploader.on("uploadBeforeSend", (block: any, data: any, headers: any) => {
    data.hash = hash;
  });

  // ‍  文件上传过程中创建进度条实时显示。
  // ‍ Real time display of progress bar created during file upload process.

  uploader.on("uploadProgress", (file: any, percentage: number) => {
    onProgress && onProgress(percentage * 100);
  });

  // ‍ 上传成功
  // ‍ Upload successful

  uploader.on("uploadSuccess", (file: any) => {
    $api
      .post(baseUrl + fileisExist, { fileHash: hash, filename: file.name })
      .then((res) => {
        console.log(res)
        if (res.data.ret == "fileAlreadyExist") {
          onUploadSuccess && onUploadSuccess(file, hash, false);
        } else {
          console.log("MxTip:post file is no exits error:2");
          onError && onError();
        }
      });
  });

  // ‍  所有文件上传成功
  // ‍ All files uploaded successfully

  uploader.on("uploadFinished", function (file: any) {
    onUploadFinished && onUploadFinished();
    // ‍ 清空队列
    // ‍ Clear the queue

    uploader.reset();
  });

  uploader.on("uploadError", (file: any, reason: any) => {
    console.log("MxTip:uploadError error:1");
    onError && onError();
  });

  uploader.on("error", (type: any) => {
    uploader.reset();
    console.log("MxTip:uploadError error:2");
    console.log("err", type);
    onError && onError();
  });
  return uploader;
}
