import type { Config } from 'jest';

const config: Config = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  setupFiles: ['dotenv/config'],
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.spec.ts', '**/?(*.)+(spec|test).ts'],
  testPathIgnorePatterns: [
    '/node_modules/',
    '.integration.spec.ts',
    'mxcad.controller.spec.ts',
    'permission-scenarios.spec.ts',
    'users.controller.spec.ts',
    'gallery.controller.spec.ts',
    'project-permission.guard.spec.ts',
    'fonts.service.spec.ts',
    'roles.controller.spec.ts',
    'permission-cache.service.spec.ts',
    'users.service.spec.ts',
    'permission.service.spec.ts',
    'fonts.controller.spec.ts',
    'gallery.service.spec.ts',
    'auth.service.spec.ts',
    'auth.controller.spec.ts',
    'cache-version.service.spec.ts',
    'file-system.controller.spec.ts',
    'jwt.strategy.spec.ts',
    'mxcad.service.spec.ts',
    'permission-test-runner.spec.ts',
    'role-inheritance.service.spec.ts',
    'jwt-auth.guard.spec.ts',
    'email.service.spec.ts',
    'cache-cleanup.scheduler.spec.ts',
  ],
  transform: {
    '^\.+\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.(t|j)s',
    '!src/**/*.d.ts',
    '!src/**/*.spec.ts',
    '!src/**/*.test.ts',
    '!src/test/**',
    '!src/main.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html', 'json-summary'],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
    './src/common/': {
      branches: 95,
      functions: 95,
      lines: 95,
      statements: 95,
    },
    './src/auth/': {
      branches: 95,
      functions: 95,
      lines: 95,
      statements: 95,
    },
    './src/users/': {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/src/test/setup.ts'],
  testTimeout: 30000,
  maxWorkers: '50%',
  verbose: true,
  detectOpenHandles: true,
  forceExit: true,
  clearMocks: true,
  restoreMocks: true,
  resetMocks: true,
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@test/(.*)$': '<rootDir>/src/test/$1',
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  snapshotResolver: '<rootDir>/jest-snapshot-resolver.js',
  snapshotSerializers: [],
};

export default config;
