/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DialogBase: typeof import('./src/components/DialogBase.vue')['default']
    FloatingPopup: typeof import('./src/components/FloatingPopup.vue')['default']
    FolderIcon: typeof import('./src/components/FileIcons/FolderIcon.vue')['default']
    LoginPromptPopup: typeof import('./src/components/LoginPromptPopup.vue')['default']
    MxIcon: typeof import('./src/components/MxIcon.vue')['default']
    MxToolbar: typeof import('./src/components/MxToolbar.vue')['default']
    NoticeDialog: typeof import('./src/components/NoticeDialog.vue')['default']
    ProjectIcon: typeof import('./src/components/FileIcons/ProjectIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareLinkSheet: typeof import('./src/components/ShareLinkSheet.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
    WorkCard: typeof import('./src/components/WorkCard.vue')['default']
  }
}

// For TSX support
declare global {
  const DialogBase: typeof import('./src/components/DialogBase.vue')['default']
  const FloatingPopup: typeof import('./src/components/FloatingPopup.vue')['default']
  const FolderIcon: typeof import('./src/components/FileIcons/FolderIcon.vue')['default']
  const LoginPromptPopup: typeof import('./src/components/LoginPromptPopup.vue')['default']
  const MxIcon: typeof import('./src/components/MxIcon.vue')['default']
  const MxToolbar: typeof import('./src/components/MxToolbar.vue')['default']
  const NoticeDialog: typeof import('./src/components/NoticeDialog.vue')['default']
  const ProjectIcon: typeof import('./src/components/FileIcons/ProjectIcon.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ShareLinkSheet: typeof import('./src/components/ShareLinkSheet.vue')['default']
  const VanActionSheet: typeof import('vant/es')['ActionSheet']
  const VanButton: typeof import('vant/es')['Button']
  const VanCell: typeof import('vant/es')['Cell']
  const VanCellGroup: typeof import('vant/es')['CellGroup']
  const VanCheckbox: typeof import('vant/es')['Checkbox']
  const VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
  const VanConfigProvider: typeof import('vant/es')['ConfigProvider']
  const VanDialog: typeof import('vant/es')['Dialog']
  const VanDropdownItem: typeof import('vant/es')['DropdownItem']
  const VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
  const VanEmpty: typeof import('vant/es')['Empty']
  const VanField: typeof import('vant/es')['Field']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanImage: typeof import('vant/es')['Image']
  const VanLoading: typeof import('vant/es')['Loading']
  const VanNavBar: typeof import('vant/es')['NavBar']
  const VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
  const VanPicker: typeof import('vant/es')['Picker']
  const VanPopover: typeof import('vant/es')['Popover']
  const VanPopup: typeof import('vant/es')['Popup']
  const VanProgress: typeof import('vant/es')['Progress']
  const VanPullRefresh: typeof import('vant/es')['PullRefresh']
  const VanRadio: typeof import('vant/es')['Radio']
  const VanRadioGroup: typeof import('vant/es')['RadioGroup']
  const VanSearch: typeof import('vant/es')['Search']
  const VanSwitch: typeof import('vant/es')['Switch']
  const VanTab: typeof import('vant/es')['Tab']
  const VanTabs: typeof import('vant/es')['Tabs']
  const VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  const WorkCard: typeof import('./src/components/WorkCard.vue')['default']
}