/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DialogBase: typeof import('./src/components/DialogBase.vue')['default']
    FloatingPopup: typeof import('./src/components/FloatingPopup.vue')['default']
    MxIcon: typeof import('./src/components/MxIcon.vue')['default']
    MxToolbar: typeof import('./src/components/MxToolbar.vue')['default']
    SharePopup: typeof import('./src/components/SharePopup.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingPanel: typeof import('vant/es')['FloatingPanel']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanTag: typeof import('vant/es')['Tag']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  }
}

// For TSX support
declare global {
  const DialogBase: typeof import('./src/components/DialogBase.vue')['default']
  const FloatingPopup: typeof import('./src/components/FloatingPopup.vue')['default']
  const MxIcon: typeof import('./src/components/MxIcon.vue')['default']
  const MxToolbar: typeof import('./src/components/MxToolbar.vue')['default']
  const SharePopup: typeof import('./src/components/SharePopup.vue')['default']
  const VanButton: typeof import('vant/es')['Button']
  const VanCell: typeof import('vant/es')['Cell']
  const VanCellGroup: typeof import('vant/es')['CellGroup']
  const VanConfigProvider: typeof import('vant/es')['ConfigProvider']
  const VanDialog: typeof import('vant/es')['Dialog']
  const VanEmpty: typeof import('vant/es')['Empty']
  const VanField: typeof import('vant/es')['Field']
  const VanFloatingPanel: typeof import('vant/es')['FloatingPanel']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanLoading: typeof import('vant/es')['Loading']
  const VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
  const VanPicker: typeof import('vant/es')['Picker']
  const VanPopover: typeof import('vant/es')['Popover']
  const VanPopup: typeof import('vant/es')['Popup']
  const VanProgress: typeof import('vant/es')['Progress']
  const VanRadio: typeof import('vant/es')['Radio']
  const VanRadioGroup: typeof import('vant/es')['RadioGroup']
  const VanTag: typeof import('vant/es')['Tag']
  const VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
}