/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_getHello'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 用户注册 */
    post: operations['AuthController_register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 用户登录 */
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 刷新Token */
    post: operations['AuthController_refreshToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 用户登出 */
    post: operations['AuthController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取用户信息 */
    get: operations['AuthController_getProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/send-verification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 发送邮箱验证码 */
    post: operations['AuthController_sendVerification'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/verify-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 验证邮箱 */
    post: operations['AuthController_verifyEmail'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/resend-verification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 重发验证码 */
    post: operations['AuthController_resendVerification'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/forgot-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 忘记密码 */
    post: operations['AuthController_forgotPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 重置密码 */
    post: operations['AuthController_resetPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/session/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['SessionController_createSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/session/user': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['SessionController_getSessionUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/session/destroy': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['SessionController_destroySession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['UsersController_findAll'];
    put?: never;
    post: operations['UsersController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['UsersController_findOne'];
    put?: never;
    post?: never;
    delete: operations['UsersController_remove'];
    options?: never;
    head?: never;
    patch: operations['UsersController_update'];
    trace?: never;
  };
  '/api/users/{id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['UsersController_updateStatus'];
    trace?: never;
  };
  '/api/users/profile/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['UsersController_getProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['UsersController_updateProfile'];
    trace?: never;
  };
  '/api/users/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 修改密码 */
    post: operations['UsersController_changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/file-system/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FileSystemController_getProjects'];
    put?: never;
    post: operations['FileSystemController_createProject'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/file-system/projects/{projectId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FileSystemController_getProject'];
    put?: never;
    post?: never;
    delete: operations['FileSystemController_deleteProject'];
    options?: never;
    head?: never;
    patch: operations['FileSystemController_updateProject'];
    trace?: never;
  };
  '/api/file-system/nodes/{parentId}/folders': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['FileSystemController_createFolder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/file-system/nodes/{nodeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FileSystemController_getNode'];
    put?: never;
    post?: never;
    delete: operations['FileSystemController_deleteNode'];
    options?: never;
    head?: never;
    patch: operations['FileSystemController_updateNode'];
    trace?: never;
  };
  '/api/file-system/nodes/{nodeId}/children': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FileSystemController_getChildren'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/file-system/nodes/{nodeId}/move': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['FileSystemController_moveNode'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/file-system/files/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['FileSystemController_uploadFile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/file-system/storage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FileSystemController_getStorageInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/files/chunkisExist': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_checkChunkExist'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/files/fileisExist': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_checkFileExist'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/files/tz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_checkTzStatus'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/files/uploadFiles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_uploadFile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/files/testupfile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_testUploadFile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/convert': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_convertServerFile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/upfile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_uploadAndConvert'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/savemxweb': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_saveMxweb'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/savedwg': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_saveDwg'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/savepdf': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_savePdf'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/print_to_pdf': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_printToPdf'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/cut_dwg': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_cutDwg'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/cut_mxweb': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_cutMxweb'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/up_ext_reference_dwg': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_uploadExtReferenceDwg'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/up_ext_reference_image': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_uploadExtReferenceImage'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/up_image': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MxCadController_uploadImage'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/mxcad/file/{filename}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MxCadController_getFile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminController_getAdminStats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/permissions/cache': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminController_getCacheStats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/permissions/cache/cleanup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AdminController_cleanupCache'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/permissions/cache/user/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['AdminController_clearUserCache'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/permissions/cache/project/{projectId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['AdminController_clearProjectCache'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/permissions/cache/file/{fileId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['AdminController_clearFileCache'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/permissions/user/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminController_getUserPermissions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 系统健康检查 */
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health/db': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 数据库健康检查 */
    get: operations['HealthController_checkDatabase'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health/storage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 存储服务健康检查 */
    get: operations['HealthController_checkStorage'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterDto: {
      /**
       * Format: email
       * @description 用户邮箱
       * @example user@example.com
       */
      email: string;
      /**
       * @description 用户名
       * @example username
       */
      username: string;
      /**
       * @description 密码
       * @example password123
       */
      password: string;
      /**
       * @description 昵称
       * @example 用户昵称
       */
      nickname?: string;
    };
    LoginDto: {
      /**
       * @description 邮箱或用户名
       * @example user@example.com
       */
      account: string;
      /**
       * @description 密码
       * @example Password123!
       */
      password: string;
    };
    UserDto: {
      /**
       * @description 用户ID
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description 用户邮箱
       * @example user@example.com
       */
      email: string;
      /**
       * @description 用户名
       * @example username
       */
      username: string;
      /**
       * @description 昵称
       * @example 用户昵称
       */
      nickname?: string;
      /**
       * @description 头像URL
       * @example https://example.com/avatar.jpg
       */
      avatar?: string;
      /**
       * @description 用户角色
       * @example USER
       * @enum {string}
       */
      role: 'ADMIN' | 'USER';
      /**
       * @description 用户状态
       * @example ACTIVE
       * @enum {string}
       */
      status: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED';
    };
    AuthResponseDto: {
      /**
       * @description 访问Token
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
       */
      accessToken: string;
      /**
       * @description 刷新Token
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
       */
      refreshToken: string;
      /** @description 用户信息 */
      user: components['schemas']['UserDto'];
    };
    AuthApiResponseDto: {
      /**
       * @description 响应状态码
       * @example SUCCESS
       * @enum {string}
       */
      code: 'SUCCESS' | 'ERROR';
      /**
       * @description 响应消息
       * @example 操作成功
       */
      message: string;
      /** @description 认证响应数据 */
      data: components['schemas']['AuthResponseDto'];
      /**
       * @description 响应时间戳
       * @example 2025-12-12T03:34:55.801Z
       */
      timestamp: string;
    };
    RefreshTokenDto: {
      /**
       * @description 刷新Token
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
       */
      refreshToken: string;
    };
    SendVerificationResponseDto: {
      /**
       * @description 操作结果
       * @example 验证邮件已发送
       */
      message: string;
    };
    SendVerificationApiResponseDto: {
      code: components['schemas']['SendVerificationResponseDto'];
      message: string;
      data: components['schemas']['SendVerificationResponseDto'];
      timestamp: string;
    };
    VerifyEmailDto: {
      /**
       * @description 邮箱地址
       * @example user@example.com
       */
      email: string;
      /**
       * @description 6位数字验证码
       * @example 123456
       */
      code: string;
    };
    VerifyEmailResponseDto: {
      /**
       * @description 操作结果
       * @example 邮箱验证成功
       */
      message: string;
    };
    VerifyEmailApiResponseDto: {
      code: components['schemas']['VerifyEmailResponseDto'];
      message: string;
      data: components['schemas']['VerifyEmailResponseDto'];
      timestamp: string;
    };
    ForgotPasswordDto: {
      /**
       * @description 邮箱地址
       * @example user@example.com
       */
      email: string;
    };
    ForgotPasswordResponseDto: {
      /** @description 消息 */
      message: string;
    };
    ForgotPasswordApiResponseDto: {
      /**
       * @description 响应状态码
       * @example SUCCESS
       * @enum {string}
       */
      code: 'SUCCESS' | 'ERROR';
      /**
       * @description 响应消息
       * @example 操作成功
       */
      message: string;
      /** @description 响应数据 */
      data: components['schemas']['ForgotPasswordResponseDto'];
      /**
       * @description 响应时间戳
       * @example 2025-12-12T03:34:55.801Z
       */
      timestamp: string;
    };
    ResetPasswordDto: {
      /**
       * @description 邮箱地址
       * @example user@example.com
       */
      email: string;
      /**
       * @description 验证码
       * @example 123456
       */
      code: string;
      /**
       * @description 新密码
       * @example NewPassword123!
       */
      newPassword: string;
    };
    ResetPasswordResponseDto: {
      /** @description 消息 */
      message: string;
    };
    ResetPasswordApiResponseDto: {
      /**
       * @description 响应状态码
       * @example SUCCESS
       * @enum {string}
       */
      code: 'SUCCESS' | 'ERROR';
      /**
       * @description 响应消息
       * @example 操作成功
       */
      message: string;
      /** @description 响应数据 */
      data: components['schemas']['ResetPasswordResponseDto'];
      /**
       * @description 响应时间戳
       * @example 2025-12-12T03:34:55.801Z
       */
      timestamp: string;
    };
    CreateUserDto: {
      /**
       * Format: email
       * @description 用户邮箱
       * @example user@example.com
       */
      email: string;
      /**
       * @description 用户名
       * @example username
       */
      username: string;
      /**
       * @description 密码
       * @example password123
       */
      password: string;
      /** @description 昵称 */
      nickname?: string;
      /** @description 头像URL */
      avatar?: string;
      /**
       * @description 用户角色
       * @default USER
       * @enum {string}
       */
      role: 'ADMIN' | 'USER';
    };
    UpdateUserDto: {
      /** @description 用户邮箱 */
      email?: string;
      /** @description 用户名 */
      username?: string;
      /** @description 密码 */
      password?: string;
      /** @description 昵称 */
      nickname?: string;
      /** @description 头像URL */
      avatar?: string;
      /**
       * @description 用户角色
       * @enum {string}
       */
      role?: 'ADMIN' | 'USER';
      /**
       * @description 用户状态
       * @enum {string}
       */
      status?: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED';
    };
    ChangePasswordDto: {
      /**
       * @description 旧密码
       * @example OldPassword123!
       */
      oldPassword: string;
      /**
       * @description 新密码
       * @example NewPassword123!
       */
      newPassword: string;
    };
    ChangePasswordResponseDto: {
      /** @description 消息 */
      message: string;
    };
    ChangePasswordApiResponseDto: {
      /**
       * @description 响应状态码
       * @example SUCCESS
       * @enum {string}
       */
      code: 'SUCCESS' | 'ERROR';
      /**
       * @description 响应消息
       * @example 操作成功
       */
      message: string;
      /** @description 响应数据 */
      data: components['schemas']['ChangePasswordResponseDto'];
      /**
       * @description 响应时间戳
       * @example 2025-12-12T03:34:55.801Z
       */
      timestamp: string;
    };
    CreateProjectDto: {
      /**
       * @description 项目名称
       * @example CAD图纸项目
       */
      name: string;
      /** @description 项目描述 */
      description?: string;
    };
    UpdateNodeDto: {
      /** @description 节点名称 */
      name?: string;
      /** @description 描述 */
      description?: string;
      /** @description 状态 */
      status?: string;
    };
    CreateFolderDto: {
      /**
       * @description 文件夹名称
       * @example 设计图纸
       */
      name: string;
    };
    MoveNodeDto: {
      /** @description 目标父节点ID */
      targetParentId: string;
    };
    ChunkExistDto: {
      /** @description 分片索引（从 0 开始） */
      chunk: number;
      /** @description 文件 MD5 哈希值 */
      fileHash: string;
      /** @description 当前分片大小（字节） */
      size: number;
      /** @description 总分片数量 */
      chunks: number;
      /** @description 原始文件名 */
      fileName: string;
      /** @description 项目ID（用于文件系统关联） */
      projectId?: string;
      /** @description 父文件夹ID（用于文件系统关联） */
      parentId?: string;
    };
    FileExistDto: {
      /** @description 原始文件名（含扩展名） */
      filename: string;
      /** @description 文件 MD5 哈希值 */
      fileHash: string;
      /** @description 项目ID（用于文件系统关联） */
      projectId?: string;
      /** @description 父文件夹ID（用于文件系统关联） */
      parentId?: string;
    };
    TzDto: {
      /** @description 文件 MD5 哈希值 */
      fileHash: string;
    };
    ConvertDto: {
      /** @description 转换参数 */
      param: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterDto'];
      };
    };
    responses: {
      /** @description 注册成功，请查收验证邮件 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description 请求参数错误 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 邮箱或用户名已存在 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      /** @description 登录成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthApiResponseDto'];
        };
      };
      /** @description 账号或密码错误 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refreshToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenDto'];
      };
    };
    responses: {
      /** @description Token刷新成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthApiResponseDto'];
        };
      };
      /** @description 无效的刷新Token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 登出成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_getProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 获取用户信息成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 未授权 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_sendVerification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 验证邮件已发送 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SendVerificationApiResponseDto'];
        };
      };
      /** @description 请求参数错误或发送过于频繁 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_verifyEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyEmailDto'];
      };
    };
    responses: {
      /** @description 邮箱验证成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VerifyEmailApiResponseDto'];
        };
      };
      /** @description 验证码无效或已过期 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_resendVerification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 验证邮件已重新发送 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SendVerificationApiResponseDto'];
        };
      };
      /** @description 请求参数错误或发送过于频繁 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_forgotPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgotPasswordDto'];
      };
    };
    responses: {
      /** @description 密码重置验证码已发送 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ForgotPasswordApiResponseDto'];
        };
      };
      /** @description 请求参数错误 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 该邮箱未注册或账号已禁用 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordDto'];
      };
    };
    responses: {
      /** @description 密码重置成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ResetPasswordApiResponseDto'];
        };
      };
      /** @description 请求参数错误 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 验证码无效或已过期 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SessionController_createSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SessionController_getSessionUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SessionController_destroySession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_findAll: {
    parameters: {
      query?: {
        /** @description 搜索关键词 */
        search?: string;
        /** @description 用户角色筛选 */
        role?: 'ADMIN' | 'USER';
        /** @description 页码 */
        page?: number;
        /** @description 每页数量 */
        limit?: number;
        /** @description 排序字段 */
        sortBy?: string;
        /** @description 排序方向 */
        sortOrder?: 'asc' | 'desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_updateStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_getProfile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordDto'];
      };
    };
    responses: {
      /** @description 密码修改成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChangePasswordApiResponseDto'];
        };
      };
      /** @description 请求参数错误 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 未授权或旧密码不正确 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 旧密码不正确 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FileSystemController_getProjects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 获取项目列表成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FileSystemController_createProject: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProjectDto'];
      };
    };
    responses: {
      /** @description 项目创建成功 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FileSystemController_getProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 获取项目详情成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FileSystemController_deleteProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 删除项目成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FileSystemController_updateProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateNodeDto'];
      };
    };
    responses: {
      /** @description 更新项目成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FileSystemController_createFolder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        parentId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateFolderDto'];
      };
    };
    responses: {
      /** @description 创建文件夹成功 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FileSystemController_getNode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 获取节点详情成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FileSystemController_deleteNode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 删除节点成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FileSystemController_updateNode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateNodeDto'];
      };
    };
    responses: {
      /** @description 更新节点成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FileSystemController_getChildren: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 获取子节点列表成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FileSystemController_moveNode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MoveNodeDto'];
      };
    };
    responses: {
      /** @description 移动节点成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FileSystemController_uploadFile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 文件上传成功 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FileSystemController_getStorageInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 获取存储空间信息成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_checkChunkExist: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChunkExistDto'];
      };
    };
    responses: {
      /** @description 检查分片是否存在 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_checkFileExist: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FileExistDto'];
      };
    };
    responses: {
      /** @description 检查文件是否存在 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_checkTzStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TzDto'];
      };
    };
    responses: {
      /** @description 检查图纸状态 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_uploadFile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file?: string;
          /** @description 文件 MD5 哈希值 */
          hash?: string;
          /** @description 原始文件名 */
          name?: string;
          /** @description 文件总大小（字节） */
          size?: number;
          /** @description 分片索引（分片上传时必填） */
          chunk?: number;
          /** @description 总分片数量（分片上传时必填） */
          chunks?: number;
          /** @description 项目ID（用于文件系统关联） */
          projectId?: string;
          /** @description 父文件夹ID（用于文件系统关联） */
          parentId?: string;
        };
      };
    };
    responses: {
      /** @description 上传文件 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_testUploadFile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 测试上传文件 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_convertServerFile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConvertDto'];
      };
    };
    responses: {
      /** @description 转换服务器文件 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_uploadAndConvert: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 上传并转换文件 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_saveMxweb: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 保存 MXWEB 到服务器 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_saveDwg: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 保存 DWG 到服务器 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_savePdf: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 保存 PDF 到服务器 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_printToPdf: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 打印为 PDF */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_cutDwg: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 裁剪 DWG */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_cutMxweb: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 裁剪 MXWEB */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_uploadExtReferenceDwg: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 上传外部参照 DWG */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_uploadExtReferenceImage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 上传外部参照图片 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_uploadImage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 上传图片 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MxCadController_getFile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        filename: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 成功获取文件 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/octet-stream': string;
        };
      };
      /** @description 文件不存在 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example -1 */
            code?: number;
            /** @example 文件不存在 */
            message?: string;
          };
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example -1 */
            code?: number;
            /** @example 访问文件失败 */
            message?: string;
          };
        };
      };
    };
  };
  AdminController_getAdminStats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_getCacheStats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_cleanupCache: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_clearUserCache: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_clearProjectCache: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_clearFileCache: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        fileId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_getUserPermissions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Health Check is successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example ok */
            status?: string;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {} */
            error?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
      /** @description The Health Check is not successful */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example error */
            status?: string;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect"
             *       }
             *     }
             */
            error?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       },
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect"
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
  };
  HealthController_checkDatabase: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 数据库连接正常 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 数据库连接失败 */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_checkStorage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 存储服务正常 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 存储服务不可用 */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}

/**
 * 外部参照预加载数据
 */
export interface PreloadingData {
  /** 是否为图纸 */
  tz: boolean;
  /** 源文件哈希值 */
  src_file_md5: string;
  /** 图片列表 */
  images: string[];
  /** 外部参照列表 */
  externalReference: string[];
}

/**
 * 外部参照文件存在性检查结果
 */
export interface CheckReferenceExistsResult {
  /** 文件是否存在 */
  exists: boolean;
}

/**
 * 字体信息
 */
export interface FontInfo {
  /** 字体文件名 */
  name: string;
  /** 文件大小（字节） */
  size: number;
  /** 文件扩展名 */
  extension: string;
  /** 后端目录是否存在 */
  existsInBackend: boolean;
  /** 前端目录是否存在 */
  existsInFrontend: boolean;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
  /** 创建者 */
  creator?: string;
}
