/**
 * pg-manager.js writePgAutoConf 单元测试
 *
 * 断言目标（部署包去 JIT 的配套配置必须真正落盘）：
 * 1. 写入 jit = off——PG 默认 jit=on，只有显式 off 才阻止加载 llvmjit.so
 * 2. port / unix_socket_directories 原有语义不被破坏
 * 3. 幂等：重复调用内容逐字节一致，不重复追加
 * 4. 原地更新已有同名 key（含 jit = on → off 的升级场景），无关配置行保留
 *
 * PG_DATA_DIR 是模块加载时确定的常量，故在 require 之前用
 * CLOUDCAD_PG_DATA_DIR 重定向到临时目录。
 */
const fs = require('fs');
const os = require('os');
const path = require('path');

const DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'pg-data-'));
process.env.CLOUDCAD_PG_DATA_DIR = DATA_DIR;
process.env.DB_PORT = '15432';
process.env.PG_SOCKET_DIR = '/var/run/pgsql';

const { writePgAutoConf } = require('../../../runtime/scripts/pg-manager');

afterAll(() => {
  fs.rmSync(DATA_DIR, { recursive: true, force: true });
});

function writeConf(text) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(path.join(DATA_DIR, 'postgresql.auto.conf'), text);
}

function readConf() {
  return fs.readFileSync(path.join(DATA_DIR, 'postgresql.auto.conf'), 'utf8');
}

describe('writePgAutoConf', () => {
  it('数据目录不存在时静默返回（不抛错、不建文件）', () => {
    fs.rmSync(DATA_DIR, { recursive: true, force: true });
    expect(() => writePgAutoConf()).not.toThrow();
    expect(
      fs.existsSync(path.join(DATA_DIR, 'postgresql.auto.conf'))
    ).toBe(false);
  });

  it('写入 jit=off / port / socket，并保留 initdb 注释头', () => {
    writeConf('# Do not edit this file manually!\n');
    writePgAutoConf();
    const content = readConf();
    expect(content).toContain('jit = off');
    expect(content).toContain('port = 15432');
    expect(content).toContain("unix_socket_directories = '/var/run/pgsql'");
    expect(content).toContain('# Do not edit this file manually!');
  });

  it('幂等：重复调用内容逐字节一致', () => {
    writeConf('');
    writePgAutoConf();
    const first = readConf();
    writePgAutoConf();
    expect(readConf()).toBe(first);
  });

  it('原地更新同名 key（升级场景 jit=on→off、port 改口），无关配置保留', () => {
    writeConf('port = 9999\n' + 'jit = on\n' + 'max_connections = 100\n');
    writePgAutoConf();
    const content = readConf();
    expect(content).toContain('port = 15432');
    expect(content).not.toContain('port = 9999');
    expect(content).toContain('jit = off');
    expect(content).not.toContain('jit = on');
    expect(content).toContain('max_connections = 100');
    expect((content.match(/jit = /g) || []).length).toBe(1);
    expect((content.match(/port = /g) || []).length).toBe(1);
  });

  it('socket 目录里的单引号被转义', () => {
    process.env.PG_SOCKET_DIR = '/tmp/a\'b';
    writeConf('');
    writePgAutoConf();
    expect(readConf()).toContain("unix_socket_directories = '/tmp/a\\'b'");
  });
});
